### ISSUE TITLE
Análise de tarefas

### ISSUE THREAD

**Issue by Gabrielle-Ribeiro** [Interacao-Humano-Computador/2020.1-Prefeitura-Municipal-de-Arco-Iris#11]
**Descrição**

Elaborar a análise de tarefas para o projeto.

**Tasks**

- [ ] Escolher 3 tarefas que se fazem no site da prefeitura.
- [ ] Descrever o fluxo para a tarefa 
- [ ] Escrever justificativa para essa análise de tarefas.

**Informações Adicionais**
