### ISSUE TITLE
Apresentação do ponto de controle 2

### ISSUE THREAD

**Issue by Gabrielle-Ribeiro** [Interacao-Humano-Computador/2020.1-Prefeitura-Municipal-de-Arco-Iris#31]
**Descrição**

Criação da apresentação com os tópicos do ponto de controle 2:
- Princípios Gerais de Projeto
- Metas de Usabilidade
- Guia de Estilo

**Tasks**

- [ ] Criação de slides
- [x] Gravação da apresentação
- [x] Subir apresentação para Youtube
- [x] Atualizar wiki com apresentação.

**Informações Adicionais**
