### ISSUE TITLE
Storyboard

### ISSUE THREAD

**Issue by giovannabbottino** [Interacao-Humano-Computador/2020.1-Prefeitura-Municipal-de-Arco-Iris#37]
**Descrição**
Adicionar arquivo de storyboard.

**Tasks**
- [x] Criação do storyboard de visualizar a prestação de contas públicas, 
- [x] Criação do storyboard de visualizar as notícias recentes sobre a cidade e 
- [x] Criação do storyboard de visualizar as informações sobre o Coronavírus na cidade.
