### ISSUE TITLE
Análise da Avaliação do Storyboard e análise de tarefas 

### ISSUE THREAD

**Issue by lgpinheiro94** [Interacao-Humano-Computador/2020.1-Prefeitura-Municipal-de-Arco-Iris#43]
**Descrição**
Realizar o teste-piloto com o objetivo de avaliar o próprio planejamento, e analisar se a avaliação possui os dados necessaários, para responder as questões que são o objetivo do estudo, permitindo que através da análise da avaliação do storyboard e análise de tarefas, tenhamos a consolidando os resultados, relatando problemas, sugerindo correções e concluindo a atividade.

**Tasks**

- [ ] Análise e revisão completa do storyboard e da análise de tarefas
- [ ] Consolidação dos resultados
- [ ] Apontamento de problemas e sugestão de correções
