### ISSUE TITLE
Refatorar o ponto de controle 3

### ISSUE THREAD

**Issue by giovannabbottino** [Interacao-Humano-Computador/2020.1-Prefeitura-Municipal-de-Arco-Iris#53]
**Descrição**
Corrigir os artefatos e os documentos gerados no ponto de controle 3. 

**Tasks**
- [ ] Adicionar informações faltando no do Planejamento da avaliação do Storyboard
- [ ] Adicionar informações faltando no Storyboard
- [ ] Adicionar informações faltando na Avaliação Storyboard e Análise de Tarefas
