### ISSUE TITLE
Avaliação Protótipo de alta fidelidade

### ISSUE THREAD

**Issue by AlineLermen** [Interacao-Humano-Computador/2020.1-Prefeitura-Municipal-de-Arco-Iris#62]
**Descrição**

Realizar a avaliação do protótipo de alta fidelidade, a partir da análise de entrevistas a serem realizadas

**Tasks**

- [x] Realizar entrevistas e adicionar no youtube
- [x] Adicionar explicação e links das entrevistas na wiki
- [x] Realizar a análise e avaliação do protótipo e colocar os resultados na wiki
