### ISSUE TITLE
Verificação dos artefatos

### ISSUE THREAD

**Issue by giovannabbottino** [Interacao-Humano-Computador/2020.1-Prefeitura-Municipal-de-Arco-Iris#63]
**Descrição**
Adicionar a verificação dos Artefatos. 

**Tasks**
Verificações
Análise de Requisitos
- [x] Verificação 01: Questionário
- [ ] Verificação 02: Perfil de usuário
- [ ] Verificação 03: Persona
- [x] Verificação 04: Princípios e diretrizes do projeto
- [ ] Verificação 05: Metas de usabilidade
- [ ] Verificação 06: Guia de estilo
- [x] Verificação 07: Análise de tarefas

Design, avaliação, desenvolvimento
- [ ] Verificação 08: Storyboards
- [ ] Verificação 09: Planejamento e avaliação dos Storyboards
- [ ] Verificação 10: Protótipos de papel
- [ ] Verificação 11: Planejamento e avaliação dos Protótipos de papel
- [ ] Verificação 12: Protótipos de alta-fidelidade
- [ ] Verificação 13: Planejamento e avaliação dos Protótipos de alta-fidelidade
- [x] Verificação 14: Planejamento e avaliação da Análise de tarefas
