### ISSUE TITLE
Perfil de usuário

### ISSUE THREAD

**Issue by Gabrielle-Ribeiro** [Interacao-Humano-Computador/2020.1-Prefeitura-Municipal-de-Arco-Iris#9]
**Descrição**

Elaborar o perfil de usuário do nosso projeto. Para isso será aplicado um questionário e depois será feita a análise do mesmo.

**Tasks**

- [x] Preparar perguntas e formulário.
- [x] Aplicar formulário.
- [x] Analisar as respostas do formulário.
- [x] Criar perfil de usuário bem como a justificativa.

**Informações Adicionais**
